#!/bin/sh
# Start/stop the Mediasearch daemon.

### BEGIN INIT INFO
# Provides:          mediasearchd
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Should-Start:      $network
# Should-Stop:       $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Mediasearch daemon
# Description:       web server for the Mediasearch daemon
### END INIT INFO

. /lib/lsb/init-functions

DAEMON=/opt/mediasearch/sbin/mediasearchd.py
PIDFILE=/opt/mediasearch/var/run/mediasearchd.pid
LOGFILE=/opt/mediasearch/var/log/mediasearchd.log
INSTDIR=/opt/mediasearch
WEBPORT=9020
WEBHOST=localhost
DBNAME=mediasearch

test -x $DAEMON || exit 0

case "$1" in
  start)
    log_daemon_msg "Starting Mediasearch daemon"
    log_progress_msg "mediasearch"

    start-stop-daemon --start --quiet --pidfile $PIDFILE --startas $DAEMON -- \
        -n $DBNAME -a $WEBHOST -p $WEBPORT -i $PIDFILE -l $LOGFILE -s $INSTDIR -d -v || true

    log_end_msg 0
    ;;

  stop)
    log_daemon_msg "Stopping Mediasearch daemon"
    log_progress_msg "mediasearch"
    start-stop-daemon --stop --quiet \
        --pidfile $PIDFILE || true

    log_end_msg 0
    ;;

  reload)
    # We don't have support for this yet.
    exit 1
    ;;

  restart|force-reload)
    $0 stop
    sleep 1
    $0 start
    ;;

  *)
    echo "Usage: $0 {start|stop|restart|force-reload}"
    exit 1

esac

exit 0
